// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: person.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloPluginClient is the client API for HelloPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloPluginClient interface {
	GetPerson(ctx context.Context, in *RequestPerson, opts ...grpc.CallOption) (*Person, error)
	GetAddressBook(ctx context.Context, in *RequestAddressBook, opts ...grpc.CallOption) (*AddressBook, error)
}

type helloPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloPluginClient(cc grpc.ClientConnInterface) HelloPluginClient {
	return &helloPluginClient{cc}
}

func (c *helloPluginClient) GetPerson(ctx context.Context, in *RequestPerson, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/tutorial.HelloPlugin/GetPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloPluginClient) GetAddressBook(ctx context.Context, in *RequestAddressBook, opts ...grpc.CallOption) (*AddressBook, error) {
	out := new(AddressBook)
	err := c.cc.Invoke(ctx, "/tutorial.HelloPlugin/GetAddressBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloPluginServer is the server API for HelloPlugin service.
// All implementations must embed UnimplementedHelloPluginServer
// for forward compatibility
type HelloPluginServer interface {
	GetPerson(context.Context, *RequestPerson) (*Person, error)
	GetAddressBook(context.Context, *RequestAddressBook) (*AddressBook, error)
	mustEmbedUnimplementedHelloPluginServer()
}

// UnimplementedHelloPluginServer must be embedded to have forward compatible implementations.
type UnimplementedHelloPluginServer struct {
}

func (UnimplementedHelloPluginServer) GetPerson(context.Context, *RequestPerson) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPerson not implemented")
}
func (UnimplementedHelloPluginServer) GetAddressBook(context.Context, *RequestAddressBook) (*AddressBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressBook not implemented")
}
func (UnimplementedHelloPluginServer) mustEmbedUnimplementedHelloPluginServer() {}

// UnsafeHelloPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloPluginServer will
// result in compilation errors.
type UnsafeHelloPluginServer interface {
	mustEmbedUnimplementedHelloPluginServer()
}

func RegisterHelloPluginServer(s grpc.ServiceRegistrar, srv HelloPluginServer) {
	s.RegisterService(&HelloPlugin_ServiceDesc, srv)
}

func _HelloPlugin_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloPluginServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.HelloPlugin/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloPluginServer).GetPerson(ctx, req.(*RequestPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _HelloPlugin_GetAddressBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAddressBook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloPluginServer).GetAddressBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tutorial.HelloPlugin/GetAddressBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloPluginServer).GetAddressBook(ctx, req.(*RequestAddressBook))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloPlugin_ServiceDesc is the grpc.ServiceDesc for HelloPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.HelloPlugin",
	HandlerType: (*HelloPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPerson",
			Handler:    _HelloPlugin_GetPerson_Handler,
		},
		{
			MethodName: "GetAddressBook",
			Handler:    _HelloPlugin_GetAddressBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}
